/* ─── Silver GYM Gym Images (using existing public image URLs) ─── */
export const GYM_IMAGES = {
  ironHouse:  'https://lh3.googleusercontent.com/aida-public/AB6AXuAv7QgNRjmoWn5WZodJ_VKAQaSCSJ0TWYHEP0E_pXrFCgV2z7Jd5hzs-JcosUQNwnoiP4vxjMkMKlPN1TtxAOSMiANsCHUS-tk-s8q6JRPCNmyEnW_prpWyBhraPIruUT3SeLosy3IdRyqOciFofNoyUfDNqPc3HKn7WdYfV9p9gkUXJF-JIfhcdO2-FCwDTwYUWRDNljhVv4M85e8gyJ04rqxl7ISLOBw2WrF_9XL7bGpXhisdgwZT',
  block35:    'https://lh3.googleusercontent.com/aida-public/AB6AXuCIpddF4yUHZkFFyDdyDNd619WlsAaGzjuHYo94Ng5eSAKfP1qimg9ipOQAcmDL0xOmr_VX8Jl2DMaBC7hh5CPRIx57naZ1yBTCQFKEujG0sExT8c_ZnDdDW8lV_5OgjL-wU59xXlhnTJe_gNsB6Ku0rnPRJhGhYJ_c9SexPx-0TlWN6yCXWxY1zaygmPyk9Xm98dmrRN8Tz22xp7efliHSRfUuqYBAq1ITCDjunkA1yP1I-jiZigDm',
  urbanFit:   'https://lh3.googleusercontent.com/aida-public/AB6AXuDWUnns9yEyi_0oKfvYG7Uf1FPB5CSm8_fOUfADE1h8jUV2AXTcEPmxVvrqX0I-1huoYfWwCcYeuCxRPEdUbfG5site_oOLbwXXqaJwZqWpLQw4aeWB2MKxTTY2TI04LjRTikp2vqL1DuPzTML9LuEnDPRLGu9vWktEn3DjQhRuWtEez_cDKU6iwIJqbTJJzW8tyA2t8dy2VRU5r5W7XqFtF1UQTnHPiCo87MZwtEoGTg1_UnbexyAd',
  powerFit:   'https://lh3.googleusercontent.com/aida-public/AB6AXuD9sSfMJY7KKbM-MHfEWhelNHV9kuy3WF8dFG6DlDVR7C0a0rah28rkLCVU0mmlZniVa4hTis88woP0n228QLl2VpqB6OCmsmab8SwVkPadz-TE7qNkRdV2MHsEzrC4_sEqFu5oJ5bsAAq7ClRY0PRmfT_sjlaIUAwxb5sswoMszOT8wtltrZEx9BUan5xOQcWXVjFZ_-p8mLhwR0fDqcfCRMYZcCNEaocHJJVJCJK03xHW8K9LQj7p',
  hero:       'https://lh3.googleusercontent.com/aida-public/AB6AXuAW1VIhpQI3RKs-ZZyXPMMuVEhv9YntXyKw3h2VyD2cNRZ46cmKGRo3_f6nKp1oNZzTybULzbWdJBky6ksIyHwl1wfe6IVgCAwMLtS6EaqnQRMYJh_HDGisidQ1a4dQR1vJ8GlsGh2mxorJ0ppt-uDCq7W0kmWHwtZ1r5iJg6Yz_9cjl5Fp_-bh9Jim_ggGuoRk45ho2g8sHOq6Gzk68orIZ12r6SlwV4Ir5h0qEXhzrQQdpheasY6g',
  cardio:     'https://lh3.googleusercontent.com/aida-public/AB6AXuDWUnns9yEyi_0oKfvYG7Uf1FPB5CSm8_fOUfADE1h8jUV2AXTcEPmxVvrqX0I-1huoYfWwCcYeuCxRPEdUbfG5site_oOLbwXXqaJwZqWpLQw4aeWB2MKxTTY2TI04LjRTikp2vqL1DuPzTML9LuEnDPRLGu9vWktEn3DjQhRuWtEez_cDKU6iwIJqbTJJzW8tyA2t8dy2VRU5r5W7XqFtF1UQTnHPiCo87MZwtEoGTg1_UnbexyAd',
  avatar:     'https://lh3.googleusercontent.com/aida-public/AB6AXuAeiWOMEJ0h1Pv4_uuJhsSsgODjCP4SzJp7E_GxfrNHhKewcUMSanlMMjGdY9T2fM8lNCt3kfNMuuBkui-74cogEGRfOKcmsNSDQDAoCCxfbw9h1ZbLZBNWEgG5IygY7WnPpUvdPuPn5otf1iafNAsDeIe0x119EWX8sE1-IU9QN1WW8CVQhNAZnolqfMzcHzRDTRlcEeGWIi_rfAvRP7X42j_Zn8_8JkmICmYDlv0ZhQi7lciSu_kz',
};

export const mockUser = {
  name: 'Alex Rahman',
  firstName: 'Alex',
  id: 'SG-2048-DA',
  plan: 'Active',
  location: 'Mirpur 10, Dhaka',
  visitsUsed: 12,
  visitsTotal: 15,
  visitsRemaining: 3,
  renewalDate: '30 August 2026',
  streak: 4,
  avatar: GYM_IMAGES.avatar,
  memberSince: 'March 2026',
  status: 'active',
};

export const AREAS = [
  { name: 'Mirpur',       gyms: 24, active: true },
  { name: 'Uttara',       gyms: 18 },
  { name: 'Gulshan',      gyms: 15 },
  { name: 'Banani',       gyms: 12 },
  { name: 'Bashundhara',  gyms: 14 },
  { name: 'Dhanmondi',    gyms: 16 },
  { name: 'Badda',        gyms: 9 },
  { name: 'Mohammadpur',  gyms: 13 },
];

export const mockGyms = [
  {
    id: '1',
    name: 'Iron House Fitness',
    slug: 'iron-house-fitness',
    verified: true,
    area: 'Mirpur 10',
    address: 'Level 4, Rahman Plaza, Mirpur 10 Circle, Dhaka 1216',
    distance: 0.7,
    eta: 8,
    rating: 4.8,
    reviewCount: 124,
    status: 'open',
    closesAt: '11:00 PM',
    opensAt: '6:00 AM',
    crowd: 'low',
    crowdPct: 28,
    plans: ['Essential', 'Active', 'Unlimited'],
    amenities: ['Strength', 'Cardio', 'Free Weights', 'AC', 'Locker', 'Shower', 'Parking', 'Trainer', 'WiFi'],
    image: GYM_IMAGES.ironHouse,
    images: [GYM_IMAGES.ironHouse, GYM_IMAGES.powerFit, GYM_IMAGES.cardio, GYM_IMAGES.urbanFit],
    description: 'A premium strength and conditioning facility in the heart of Mirpur 10. Iron House is equipped with high-grade machines, a free-weight zone, functional training area, and a clean, focused training environment.',
    mapPin: { x: '45%', y: '38%' },
    hours: [
      { day: 'Monday', time: '6:00 AM – 11:00 PM' },
      { day: 'Tuesday', time: '6:00 AM – 11:00 PM' },
      { day: 'Wednesday', time: '6:00 AM – 11:00 PM' },
      { day: 'Thursday', time: '6:00 AM – 11:00 PM' },
      { day: 'Friday', time: '8:00 AM – 10:00 PM' },
      { day: 'Saturday', time: '7:00 AM – 10:00 PM' },
      { day: 'Sunday', time: '7:00 AM – 9:00 PM' },
    ],
    crowdByHour: [10, 15, 12, 8, 5, 40, 75, 85, 60, 45, 55, 70, 80, 65, 50, 60, 90, 95, 80, 60, 40, 20, 10, 5],
    trainers: [
      { name: 'Rakib Hasan', specialty: 'Strength & Conditioning', experience: '5 yrs' },
      { name: 'Farhana Begum', specialty: 'Cardio & Functional', experience: '3 yrs' },
    ],
    reviews: [
      { author: 'Tanvir Ahmed', rating: 5, text: 'Best gym in Mirpur. Equipment is top-notch and always clean.', date: '2 days ago' },
      { author: 'Sadia Islam', rating: 4, text: 'Great crowd management. Never too busy when I visit.', date: '1 week ago' },
    ],
  },
  {
    id: '2',
    name: 'PowerFit Mirpur',
    slug: 'powerfit-mirpur',
    verified: true,
    area: 'Mirpur 12',
    address: 'Shop 12, Mirpur 12 Main Road, Dhaka 1216',
    distance: 0.9,
    eta: 12,
    rating: 4.6,
    reviewCount: 89,
    status: 'open',
    closesAt: '11:00 PM',
    opensAt: '6:00 AM',
    crowd: 'low',
    crowdPct: 32,
    plans: ['Active', 'Unlimited'],
    amenities: ['Strength', 'Functional', 'AC', 'Locker', 'Trainer'],
    image: GYM_IMAGES.powerFit,
    images: [GYM_IMAGES.powerFit, GYM_IMAGES.ironHouse, GYM_IMAGES.cardio, GYM_IMAGES.block35],
    description: 'Functional and strength training facility with modern equipment and expert trainers.',
    mapPin: { x: '38%', y: '52%' },
    hours: [{ day: 'Monday', time: '6:00 AM – 11:00 PM' }, { day: 'Tuesday', time: '6:00 AM – 11:00 PM' }, { day: 'Wednesday', time: '6:00 AM – 11:00 PM' }, { day: 'Thursday', time: '6:00 AM – 11:00 PM' }, { day: 'Friday', time: '8:00 AM – 9:00 PM' }, { day: 'Saturday', time: '7:00 AM – 10:00 PM' }, { day: 'Sunday', time: 'Closed' }],
    crowdByHour: [5, 8, 6, 4, 2, 30, 65, 80, 55, 40, 50, 65, 75, 55, 45, 55, 85, 90, 70, 50, 30, 15, 5, 2],
    trainers: [{ name: 'Saiful Islam', specialty: 'Powerlifting', experience: '7 yrs' }],
    reviews: [{ author: 'Mehedi Hasan', rating: 5, text: 'Great for strength training. Trainers are super helpful.', date: '3 days ago' }],
  },
  {
    id: '3',
    name: 'Block 35 Fitness',
    slug: 'block-35-fitness',
    verified: true,
    area: 'Gulshan 2',
    address: 'Block 35, Gulshan Avenue, Dhaka 1212',
    distance: 8.5,
    eta: 35,
    rating: 4.9,
    reviewCount: 312,
    status: 'open',
    closesAt: '12:00 AM',
    opensAt: '6:00 AM',
    crowd: 'moderate',
    crowdPct: 58,
    plans: ['Unlimited'],
    amenities: ['Strength', 'Cardio', 'Pool', 'Sauna', 'AC', 'Locker', 'Shower', 'Parking', 'Trainer', 'WiFi', 'Women Friendly'],
    image: GYM_IMAGES.block35,
    images: [GYM_IMAGES.block35, GYM_IMAGES.urbanFit, GYM_IMAGES.ironHouse, GYM_IMAGES.cardio],
    description: 'Premium full-service gym in Gulshan. Includes a 25m pool, sauna, and a women-friendly zone.',
    mapPin: { x: '72%', y: '28%' },
    hours: [{ day: 'Monday', time: '6:00 AM – 12:00 AM' }, { day: 'Tuesday', time: '6:00 AM – 12:00 AM' }, { day: 'Wednesday', time: '6:00 AM – 12:00 AM' }, { day: 'Thursday', time: '6:00 AM – 12:00 AM' }, { day: 'Friday', time: '7:00 AM – 11:00 PM' }, { day: 'Saturday', time: '7:00 AM – 11:00 PM' }, { day: 'Sunday', time: '8:00 AM – 10:00 PM' }],
    crowdByHour: [5, 10, 8, 5, 3, 35, 60, 70, 50, 45, 55, 70, 85, 75, 65, 70, 90, 95, 85, 70, 50, 30, 15, 8],
    trainers: [],
    reviews: [{ author: 'Nadia Chowdhury', rating: 5, text: 'The pool and sauna make this worth every taka.', date: '5 days ago' }],
  },
  {
    id: '4',
    name: 'Urban Strength',
    slug: 'urban-strength',
    verified: true,
    area: 'Banani',
    address: 'Road 11, Banani DOHS, Dhaka 1213',
    distance: 6.2,
    eta: 28,
    rating: 4.7,
    reviewCount: 204,
    status: 'open',
    closesAt: '10:00 PM',
    opensAt: '7:00 AM',
    crowd: 'busy',
    crowdPct: 76,
    plans: ['Active', 'Unlimited'],
    amenities: ['Strength', 'Cardio', 'Yoga', 'AC', 'Locker', 'Shower', 'Women Friendly'],
    image: GYM_IMAGES.urbanFit,
    images: [GYM_IMAGES.urbanFit, GYM_IMAGES.block35, GYM_IMAGES.powerFit, GYM_IMAGES.cardio],
    description: 'Modern urban gym with a focus on strength and yoga. Popular with young professionals in Banani.',
    mapPin: { x: '63%', y: '35%' },
    hours: [{ day: 'Monday', time: '7:00 AM – 10:00 PM' }, { day: 'Tuesday', time: '7:00 AM – 10:00 PM' }, { day: 'Wednesday', time: '7:00 AM – 10:00 PM' }, { day: 'Thursday', time: '7:00 AM – 10:00 PM' }, { day: 'Friday', time: '8:00 AM – 9:00 PM' }, { day: 'Saturday', time: '7:00 AM – 9:00 PM' }, { day: 'Sunday', time: '8:00 AM – 8:00 PM' }],
    crowdByHour: [0, 0, 0, 0, 0, 0, 25, 55, 45, 35, 40, 60, 75, 65, 55, 65, 85, 90, 80, 60, 30, 10, 0, 0],
    trainers: [{ name: 'Lamia Hossain', specialty: 'Yoga & Mobility', experience: '4 yrs' }],
    reviews: [{ author: 'Imran Kabir', rating: 4, text: 'Great location and friendly staff.', date: '1 week ago' }],
  },
];

export const mockActivity = [
  { id: 1, type: 'checkin', gym: 'Iron House Fitness', gymId: '1', date: 'Today', time: '7:12 PM', duration: '1h 18m' },
  { id: 2, type: 'checkin', gym: 'PowerFit Mirpur', gymId: '2', date: 'Tuesday', time: '8:04 PM', duration: '1h 15m' },
  { id: 3, type: 'achievement', title: 'Weekly goal reached', date: 'Monday', time: '11:59 PM' },
  { id: 4, type: 'checkin', gym: 'Iron House Fitness', gymId: '1', date: 'Monday', time: '7:30 AM', duration: '1h 05m' },
  { id: 5, type: 'checkin', gym: 'Urban Strength', gymId: '4', date: 'Saturday', time: '9:15 AM', duration: '1h 30m' },
  { id: 6, type: 'checkin', gym: 'Iron House Fitness', gymId: '1', date: 'Thursday', time: '6:45 PM', duration: '1h 10m' },
];

export const weeklyData = [
  { day: 'Mon', workouts: 1, min: 65 },
  { day: 'Tue', workouts: 1, min: 75 },
  { day: 'Wed', workouts: 0, min: 0 },
  { day: 'Thu', workouts: 1, min: 70 },
  { day: 'Fri', workouts: 0, min: 0 },
  { day: 'Sat', workouts: 1, min: 90 },
  { day: 'Sun', workouts: 0, min: 0 },
];

export const rewards = [
  { id: 1, title: 'Consistent', desc: '12 workouts this month', icon: '🏅', achieved: true },
  { id: 2, title: '4-Day Streak', desc: '4 consecutive days', icon: '🔥', achieved: true },
  { id: 3, title: 'Explorer', desc: 'Visit 5 different gyms', progress: 3, goal: 5, icon: '🗺️', achieved: false },
  { id: 4, title: 'Early Bird', desc: '5 workouts before 8 AM', progress: 2, goal: 5, icon: '🌅', achieved: false },
];

export const plans = [
  {
    id: 'essential',
    name: 'Essential',
    price: 1990,
    visits: 8,
    gymTier: 'Essential gyms',
    features: ['8 visits/month', 'Essential tier gyms', 'QR check-in', 'Basic activity tracking', 'Email support'],
    missing: ['Premium gyms', 'Plan freeze', 'Advanced analytics', 'Priority support'],
  },
  {
    id: 'active',
    name: 'Active',
    price: 3490,
    visits: 15,
    gymTier: 'Essential + Active gyms',
    recommended: true,
    features: ['15 visits/month', 'Essential + Active tier gyms', 'QR check-in', 'Full activity tracking', 'Plan freeze (1/yr)', 'Advanced analytics', 'Priority support'],
    missing: ['Unlimited premium gyms'],
  },
  {
    id: 'unlimited',
    name: 'Unlimited',
    price: 5990,
    visits: '∞',
    gymTier: 'All gym tiers',
    features: ['Unlimited visits', 'All gym tiers (Essential, Active, Premium)', 'QR check-in', 'Full activity tracking', 'Unlimited plan freeze', 'Advanced analytics', 'Priority support', 'Guest pass (1/mo)'],
    missing: [],
  },
];

export const ownerData = {
  gymName: 'Iron House Fitness',
  todayCheckins: 34,
  currentVisitors: 18,
  monthlyVisits: 426,
  estimatedPayout: 42600,
  avgRating: 4.8,
  recentCheckins: [
    { name: 'Alex Rahman', plan: 'Active', time: '7:14 PM', status: 'approved' },
    { name: 'Nadia Islam', plan: 'Unlimited', time: '7:09 PM', status: 'approved' },
    { name: 'Tahmid Hasan', plan: 'Essential', time: '6:58 PM', status: 'approved' },
    { name: 'Sadia Akter', plan: 'Active', time: '6:45 PM', status: 'approved' },
    { name: 'Rifat Hossain', plan: 'Unlimited', time: '6:30 PM', status: 'approved' },
  ],
};

export const adminData = {
  activeMembers: 12450,
  partnerGyms: 124,
  checkinsToday: 1892,
  mrr: 4200000,
  pendingApplications: 7,
  supportIssues: 12,
};
